import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const robot = Roboto_Flex({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${robot.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col items-center px-1 bg-background">
        <Header />
        {children}
      </body>
    </html>
  );
}
